
from displayable.misc import require_request, ArgumentError
from django import template


register = template.Library()

#todo: already deprecated

@register.simple_tag(name = 'summary', takes_context = True)
@require_request
def summary(context, request, summarizable, **kwargs):
	"""
		Display a summary of an object, generated by that object's .summary method.
	"""
	if summarizable == '':
		raise ArgumentError('{% summary %} tag invoked with empty string argument; this likely means that the ' +
			'variable passed to {% summary %} was not found')
	if not hasattr(summarizable, 'summary'):
		raise ArgumentError('{% summary %} tag invoked with an object that does not have a .summary method; ' +
			'create a method that takes context and request, and returns a rendered summary of the object')
	if not callable(getattr(summarizable, 'summary', None)):
		raise ArgumentError('{% summary %} tag invoked with an object whose .summary property is not callable')
	return summarizable.summary(
		context = context,
		request = request,
		**kwargs
	)


